---
- name: 
  hosts: vault-host
  become: true

  tasks:
    - name: install jq
      apt:
        name: jq
    
    - name: create the signer token
      shell: |
        vault token create -ttl=87600h -policy=ssh-signer-management -orphan -format json | jq --raw-output .auth.client_token
      register: result
      changed_when: false
      environment: "{{ vault_env_root }}"
    
    - name: reset vault_ssh_signer_mgmt_token
      set_fact:
        vault_ssh_signer_mgmt_token: "{{ result.stdout }}"
