---
# Playbook for setting up a HAProxy load balancing server.

- name: Set up load-balancing servers
  hosts: load-balancer
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: load-balancer
      tags: 'load-balancer'

    - role: consul-template
      tags: 'consul-template'

    - role: node-exporter
      tags: 'node-exporter'
